print("STUDENT DETAILS")
print("Roll No:- 32")
print("Name:- Rutvik Kamani")
print("Age :- 20")
print("Date of Birth :- 12/12/2001")
print("Address :- To :- Gathila , Ta :- Vanthali , Dis :- Junagadh")
print("Email id :- rutvikkamani28@gmail.com")
print("Phone No :- 9016999067")
print("Branch of Stydy :- MCA")
print("College :- School of Engineering")
print("University :- RK University")
print("City :- Junagadh")
print("State :- Gujarat")
print("country :- Indian")